// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_overlap
List rcpp_overlap(List v, int t);
RcppExport SEXP _SelectSim_rcpp_overlap(SEXP vSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_overlap(v, t));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_w_overlap
List rcpp_w_overlap(List v, NumericMatrix w, int t);
RcppExport SEXP _SelectSim_rcpp_w_overlap(SEXP vSEXP, SEXP wSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_w_overlap(v, w, t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SelectSim_rcpp_overlap", (DL_FUNC) &_SelectSim_rcpp_overlap, 2},
    {"_SelectSim_rcpp_w_overlap", (DL_FUNC) &_SelectSim_rcpp_w_overlap, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SelectSim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
