#' Lung adenocarcinoma from TCGA cohort as selectX run object 
#'
#' A dataset containing the genome alteration matrix and tumor mutation burden along with sample,alteration annotation as list object
#'
#'
#' @docType data
#' @keywords datasets
#' @name luad_run_data
#' @usage data(luad_run_data)
#' @format A list object with GAMs and TMBs along with sample & alteration annotations.
NULL


#' Lung adenocarcinoma from TCGA cohort as selectX run results
#'
#' Result of LUAD generated by selectX with selectX run done at min.freq=10.
#'
#'
#' @docType data
#' @keywords datasets
#' @name luad_result
#' @usage data(luad_result)
#' @format A dataframe
NULL



#' Lung adenocarcinoma MAF from TCGA cohort 
#'
#' MAF file of LUAD from TCGA
#'
#'
#' @docType data
#' @keywords datasets
#' @name luad_maf
#' @usage data(luad_maf)
#' @format A dataframe
NULL


#' OncoKB v3.9 cancer genes
#'
#' cancer genes list
#'
#'
#' @docType data
#' @keywords datasets
#' @name oncokb_genes
#' @usage data(oncokb_genes)
#' @format A list
NULL


#' OncoKB v3.9 cancer genes consider for truncating mutations
#'
#' cancer genes list consider for truncating mutations
#'
#'
#' @docType data
#' @keywords datasets
#' @name oncokb_truncating_genes
#' @usage data(oncokb_truncating_genes)
#' @format A list
NULL


#' OncoKB v3.9 cancer genes
#'
#' A dataframe cancer genes with missense mutation annotations
#'
#'
#' @docType data
#' @keywords datasets
#' @name variant_catalogue
#' @usage data(variant_catalogue)
#' @format A dataframe
NULL