#' Lung adenocarcinoma from TCGA cohort as SelectSim run object
#'
#' Pre-processed TCGA LUAD data ready to pass directly to \code{selectX()}.
#'
#' @docType data
#' @keywords datasets
#' @name luad_run_data
#' @usage data(luad_run_data)
#' @format A named list with four elements:
#' \describe{
#'   \item{M}{A named list containing:
#'     \describe{
#'       \item{M}{A named list of binary alteration matrices (genes x samples),
#'         one per alteration type (e.g., \code{missense}, \code{truncating}).}
#'       \item{tmb}{A named list of data frames, one per alteration type, each
#'         with columns \code{sample} (character) and \code{mutation} (integer
#'         TMB count).}
#'     }
#'   }
#'   \item{sample.class}{Named character vector of sample-type annotations
#'     (length = number of samples). Names are sample IDs.}
#'   \item{alteration.class}{Named character vector of alteration-type annotations
#'     (length = number of genes). Names are gene symbols.}
#' }
NULL


#' Lung adenocarcinoma from TCGA cohort as SelectSim run results
#'
#' Result of LUAD generated by SelectSim with SelectSim run done at min.freq=10.
#'
#'
#' @docType data
#' @keywords datasets
#' @name luad_result
#' @usage data(luad_result)
#' @format A dataframe
NULL



#' Lung adenocarcinoma MAF from TCGA cohort 
#'
#' MAF file of LUAD from TCGA
#'
#'
#' @docType data
#' @keywords datasets
#' @name luad_maf
#' @usage data(luad_maf)
#' @format A dataframe
NULL


#' OncoKB v3.9 cancer genes
#'
#' cancer genes list
#'
#'
#' @docType data
#' @keywords datasets
#' @name oncokb_genes
#' @usage data(oncokb_genes)
#' @format A list
NULL


#' OncoKB v3.9 cancer genes consider for truncating mutations
#'
#' cancer genes list consider for truncating mutations
#'
#'
#' @docType data
#' @keywords datasets
#' @name oncokb_truncating_genes
#' @usage data(oncokb_truncating_genes)
#' @format A list
NULL


#' OncoKB v3.9 cancer genes
#'
#' A dataframe cancer genes with missense mutation annotations
#'
#'
#' @docType data
#' @keywords datasets
#' @name variant_catalogue
#' @usage data(variant_catalogue)
#' @format A dataframe
NULL